[phases.setup]
cacheDirectories = ["/root/.cache/pip"]
commands = [
    "apt-get update",
    "apt-get install -y --no-install-recommends python3-dev gcc"
]

[phases.install]
commands = [
    "python -m pip install --user --no-cache-dir -r requirements.txt"
]

[phases.build]
commands = []

[start]
command = "python -m uvicorn app:app --host 0.0.0.0 --port ${PORT:-8000}"
