[phases.setup]
cacheDirectories = ["/root/.cache/pip"]
commands = [
    "apt-get update"
]

[phases.install]
commands = [
    "python -m pip install --user --no-cache-dir -r requirements.txt"
]

[phases.build]
commands = []  # No separate build phase needed
